######################################################################
# Automatically generated by qmake (3.0) sam. 11. mai 13:49:46 2013
######################################################################

QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = memory
INCLUDEPATH += .

# Input
HEADERS += Memory.h
SOURCES += Memory.cpp

TRANSLATIONS += memory_fr.ts
CODECFORTR = ISO-8859-1
