######################################################################
# Automatically generated by qmake (2.01a) lun. 29. juin 20:41:53 2009
######################################################################

TEMPLATE = app
TARGET = memory
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += release
DESTDIR = ./

# Input
HEADERS += Memory.h
SOURCES += Memory.cpp

TRANSLATIONS = memory.ts
CODECFORTR = UTF-8
